swagger: "2.0"
info:
  title: Bookshelf Service
  description: Support to rent books in your office bookshelf
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /people:
    get:
      tags:
      - people
      summary: list people
      description: list
      operationId: people#list
      parameters:
      - name: _start
        in: query
        required: false
        type: integer
      - name: _end
        in: query
        required: false
        type: integer
      - name: _order
        in: query
        required: false
        type: string
        enum:
        - ASC
        - DESC
      - name: _sort
        in: query
        required: false
        type: string
      - name: q
        in: query
        required: false
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PeopleListResponseBody'
            required:
            - people
          headers:
            X-Total-Count:
              type: string
      schemes:
      - http
    post:
      tags:
      - people
      summary: create people
      description: create
      operationId: people#create
      parameters:
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PeopleCreateRequestBody'
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/PeopleCreateResponseBody'
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/Peoplecreate_validation_error_response_body'
      schemes:
      - http
  /people/{id}:
    get:
      tags:
      - people
      summary: show people
      description: show
      operationId: people#show
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PeopleShowResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/Peopleshow_not_found_response_body'
      schemes:
      - http
    put:
      tags:
      - people
      summary: update people
      description: update
      operationId: people#update
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      - name: UpdateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PeopleUpdateRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PeopleUpdateResponseBody'
            required:
            - name
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/Peopleupdate_validation_error_response_body'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/Peopleupdate_not_found_response_body'
      schemes:
      - http
    delete:
      tags:
      - people
      summary: delete people
      description: delete
      operationId: people#delete
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PeopleDeleteResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/Peopledelete_not_found_response_body'
      schemes:
      - http
definitions:
  PeopleCreateRequestBody:
    title: PeopleCreateRequestBody
    type: object
    properties:
      memo:
        type: string
        example: Necessitatibus voluptates ut labore ut est blanditiis.
      name:
        type: string
        example: Sit et.
    example:
      memo: Autem numquam nesciunt rem sunt.
      name: Magni illum quia distinctio.
    required:
    - name
  PeopleCreateResponseBody:
    title: 'Mediatype identifier: application/vnd.person+json; view=default'
    type: object
    properties:
      id:
        type: integer
        example: 7196472068798786997
        format: int64
      name:
        type: string
        example: Accusamus odio sint tenetur rerum libero.
    description: CreateResponseBody result type (default view)
    example:
      id: 3684579061264811198
      name: Quo eaque quos asperiores corrupti.
  PeopleDeleteResponseBody:
    title: 'Mediatype identifier: application/vnd.person+json; view=default'
    type: object
    properties:
      id:
        type: integer
        example: 5801866388439563789
        format: int64
      name:
        type: string
        example: Culpa quia odit ab eos.
    description: DeleteResponseBody result type (default view)
    example:
      id: 2487679091340826885
      name: Molestiae adipisci officiis voluptatum ex.
  PeopleListResponseBody:
    title: PeopleListResponseBody
    type: object
    properties:
      people:
        $ref: '#/definitions/PersonResponseBodyCollection'
    example:
      people:
      - id: 5482678800781459665
        memo: Laudantium quae non voluptas.
        name: Ex quidem fuga nesciunt.
      - id: 5482678800781459665
        memo: Laudantium quae non voluptas.
        name: Ex quidem fuga nesciunt.
      - id: 5482678800781459665
        memo: Laudantium quae non voluptas.
        name: Ex quidem fuga nesciunt.
    required:
    - people
  PeopleShowResponseBody:
    title: 'Mediatype identifier: application/vnd.person+json; view=default'
    type: object
    properties:
      id:
        type: integer
        example: 7659659041397569108
        format: int64
      name:
        type: string
        example: Provident id ullam iure.
    description: ShowResponseBody result type (default view)
    example:
      id: 6893194893223765274
      name: Necessitatibus accusantium error.
  PeopleUpdateRequestBody:
    title: PeopleUpdateRequestBody
    type: object
    properties:
      memo:
        type: string
        example: Sint molestiae id consectetur quod.
      name:
        type: string
        example: Atque eius repudiandae vel enim sit ut.
    example:
      memo: Dignissimos ullam eveniet fugiat itaque eos quia.
      name: Occaecati sit unde sed eos consequatur.
    required:
    - name
  PeopleUpdateResponseBody:
    title: PeopleUpdateResponseBody
    type: object
    properties:
      memo:
        type: string
        example: Dolorem cupiditate dolores provident rerum omnis.
      name:
        type: string
        example: Quisquam quis quia.
    example:
      memo: Optio illo ut velit.
      name: Minima cupiditate dolor quia fugit.
    required:
    - name
  Peoplecreate_validation_error_response_body:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Person Validation Error (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  Peopledelete_not_found_response_body:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Person not found (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  Peopleshow_not_found_response_body:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Person not found (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  Peopleupdate_not_found_response_body:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Person not found (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  Peopleupdate_validation_error_response_body:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Person Validation Error (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  PersonResponseBody:
    title: 'Mediatype identifier: application/vnd.person+json; view=default'
    type: object
    properties:
      id:
        type: integer
        example: 1049207802822363720
        format: int64
      name:
        type: string
        example: Nemo temporibus reprehenderit et quia.
    description: PersonResponseBody result type (default view)
    example:
      id: 9215743287182142485
      name: Id assumenda vel.
  PersonResponseBodyCollection:
    title: 'Mediatype identifier: application/vnd.person+json; type=collection; view=default'
    type: array
    items:
      $ref: '#/definitions/PersonResponseBody'
    description: PersonCollectionResponseBody is the result type for an array of PersonResponseBody
      (default view)
    example:
    - id: 5482678800781459665
      memo: Laudantium quae non voluptas.
      name: Ex quidem fuga nesciunt.
    - id: 5482678800781459665
      memo: Laudantium quae non voluptas.
      name: Ex quidem fuga nesciunt.
    - id: 5482678800781459665
      memo: Laudantium quae non voluptas.
      name: Ex quidem fuga nesciunt.
    - id: 5482678800781459665
      memo: Laudantium quae non voluptas.
      name: Ex quidem fuga nesciunt.
